### ISSUE TITLE
Issue using this with Pods in storyboard

### ISSUE THREAD

**Issue by satyam90** [cheebow/PlaceholderTextView#1]
I added this control to my project through Pods.
I'm using text view in storyboard and I set the control to PlaceholderTextView.
When I'm porting it in my swift class and creating outlet, its throwing error.
`"import PlaceholderTextView"` is fine, but     `@IBOutlet weak var commentText: PlaceholderTextView!` is throwing error as "Use of undeclared type 'PlaceholderTextView'

**Comment by cheebow** [comment]
Thank you.
Fixed in v.0.2.0
